// ─────────────────────────────────────────────────────────────
// seed/data.js  — Semua data dummy untuk seed
// ─────────────────────────────────────────────────────────────

// ── SETTINGS ─────────────────────────────────────────────────
export const SETTINGS = {
  dpt: {
    total:       1247,
    rincian: {
      rt01: 300,
      rt02: 450,
      rt03: 497,
    },
    updatedAt: new Date(),
  },

  pemilihan: {
    nama:          'Pemilihan Ketua RW 05 & RT 01–03',
    wilayah:       'RW 05, Kelurahan Menteng, Jakarta Pusat',
    tanggal:       '2026-04-25',
    jamBuka:       '08:00',
    jamTutup:      '17:00',
    status:        'berlangsung',   // 'belum_mulai' | 'berlangsung' | 'selesai'
    periode:       '2026–2029',
    kategori:      ['rw', 'rt1', 'rt2', 'rt3'],
    updatedAt:     new Date(),
  },

  keamanan: {
    enkripsi:           'AES-256',
    blockchain:         true,
    otpAktif:           true,
    maxPercobaanLogin:  3,
    lockoutMenit:       15,
    updatedAt:          new Date(),
  },
};

// ── KANDIDAT ──────────────────────────────────────────────────
export const KANDIDAT = [
  // ── Ketua RW 05 ──────────────────────────────────────
  {
    id:            'kandidat-bs',
    nama:          'Budi Santoso',
    ini:           'BS',
    kategori:      'rw',
    kategoriLabel: 'Ketua RW 05',
    jabatan:       'Calon Ketua RW 05',
    nomorUrut:     1,
    usia:          48,
    ttl:           'Jakarta, 14 Maret 1976',
    pendidikan:    'S1 Teknik Sipil — Universitas Indonesia',
    pekerjaan:     'Wiraswasta / Kontraktor',
    alamat:        'Jl. Melati No. 12, RT 02',
    pengalaman:    'Ketua RT 02 (2020–2023), Anggota BPD Kelurahan 2019–2022',
    visi:          'Mewujudkan RW 05 yang aman, bersih, dan sejahtera melalui gotong royong warga.',
    misi: [
      'Meningkatkan keamanan lingkungan dengan sistem ronda terjadwal',
      'Membangun fasilitas umum yang layak dan merata di setiap RT',
      'Mendorong UMKM warga melalui program pelatihan dan pendampingan',
      'Digitalisasi administrasi kependudukan RW',
    ],
    program:  ['Keamanan', 'Lingkungan', 'Digitalisasi', 'Sosial'],
    bg:       '#DBEAFE', tx: '#1D4ED8',
    bar:      '#1558B0', barEnd: '#3B82F6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-sr',
    nama:          'Siti Rahayu',
    ini:           'SR',
    kategori:      'rw',
    kategoriLabel: 'Ketua RW 05',
    jabatan:       'Calon Ketua RW 05',
    nomorUrut:     2,
    usia:          44,
    ttl:           'Semarang, 22 Juli 1980',
    pendidikan:    'S1 Kesehatan Masyarakat — Universitas Diponegoro',
    pekerjaan:     'Bidan Puskesmas Kecamatan',
    alamat:        'Jl. Dahlia No. 7, RT 01',
    pengalaman:    'Ketua PKK RT 01 (2021–2024), Kader Posyandu sejak 2015',
    visi:          'Menjadikan RW 05 sebagai lingkungan sehat, inklusif, dan berdaya untuk semua warga.',
    misi: [
      'Meningkatkan akses layanan kesehatan gratis bagi lansia dan balita',
      'Membentuk Posyandu mandiri di setiap RT',
      'Memperkuat peran perempuan dalam kepemimpinan lingkungan',
      'Menata infrastruktur jalan dan drainase bersama dinas terkait',
    ],
    program:  ['Kesehatan', 'Pemberdayaan', 'Infrastruktur', 'Pendidikan'],
    bg:       '#CCFBF1', tx: '#0F766E',
    bar:      '#0F766E', barEnd: '#14B8A6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-af',
    nama:          'Ahmad Fauzi',
    ini:           'AF',
    kategori:      'rw',
    kategoriLabel: 'Ketua RW 05',
    jabatan:       'Calon Ketua RW 05',
    nomorUrut:     3,
    usia:          52,
    ttl:           'Jakarta, 5 Januari 1972',
    pendidikan:    'SMA / Sederajat',
    pekerjaan:     'Pedagang & Tokoh Masyarakat',
    alamat:        'Jl. Kenanga No. 3, RT 03',
    pengalaman:    'Ketua RW 05 (2017–2020), Penggagas pasar warga RT 03',
    visi:          'Mengembalikan kebersamaan dan nilai gotong royong yang telah menjadi fondasi RW 05.',
    misi: [
      'Menghidupkan kembali tradisi musyawarah warga bulanan',
      'Menjaga stabilitas iuran dan transparansi kas RW',
      'Mendukung pedagang kaki lima warga agar tertib dan berdaya',
      'Memperkuat hubungan antar RT melalui kegiatan bersama',
    ],
    program:  ['Kebersamaan', 'Transparansi', 'Ekonomi Lokal', 'Budaya'],
    bg:       '#FFEDD5', tx: '#9A3412',
    bar:      '#EA580C', barEnd: '#F97316',
    votes:    0, pct: 0, status: 'pesaing',
  },

  // ── Ketua RT 01 ───────────────────────────────────────
  {
    id:            'kandidat-dk',
    nama:          'Dewi Kartika',
    ini:           'DK',
    kategori:      'rt1',
    kategoriLabel: 'Ketua RT 01',
    jabatan:       'Calon Ketua RT 01',
    nomorUrut:     1,
    usia:          36,
    ttl:           'Jakarta, 10 November 1988',
    pendidikan:    'S1 Akuntansi — Universitas Trisakti',
    pekerjaan:     'Staf Keuangan Swasta',
    alamat:        'Jl. Anggrek No. 4, RT 01',
    pengalaman:    'Bendahara RT 01 (2022–2025)',
    visi:          'Menjadikan RT 01 yang tertib, bersih, dan warganya saling peduli.',
    misi: [
      'Mengelola kas RT secara transparan dan akuntabel',
      'Meningkatkan kebersihan lingkungan dengan jadwal piket warga',
      'Memfasilitasi kegiatan sosial dan keagamaan secara rutin',
      'Mempercepat pengurusan administrasi kependudukan warga',
    ],
    program:  ['Keuangan', 'Kebersihan', 'Sosial', 'Administrasi'],
    bg:       '#DBEAFE', tx: '#1D4ED8',
    bar:      '#1558B0', barEnd: '#3B82F6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-hw',
    nama:          'Hendra Wijaya',
    ini:           'HW',
    kategori:      'rt1',
    kategoriLabel: 'Ketua RT 01',
    jabatan:       'Calon Ketua RT 01',
    nomorUrut:     2,
    usia:          41,
    ttl:           'Bogor, 3 Juni 1983',
    pendidikan:    'S1 Hukum — Universitas Pancasila',
    pekerjaan:     'Paralegal / Konsultan Hukum',
    alamat:        'Jl. Anggrek No. 19, RT 01',
    pengalaman:    'Sekretaris RT 01 (2021–2024), Paralegal LBH Jakarta',
    visi:          'Membangun RT 01 yang aman secara hukum dan terlindungi hak-hak warganya.',
    misi: [
      'Memberikan pendampingan hukum gratis bagi warga yang membutuhkan',
      'Memastikan setiap warga memiliki dokumen kependudukan yang lengkap',
      'Menyelesaikan perselisihan warga secara musyawarah dan adil',
      'Mengoptimalkan dana RT untuk infrastruktur yang merata',
    ],
    program:  ['Hukum', 'Dokumen', 'Mediasi', 'Infrastruktur'],
    bg:       '#CCFBF1', tx: '#0F766E',
    bar:      '#0F766E', barEnd: '#14B8A6',
    votes:    0, pct: 0, status: 'pesaing',
  },

  // ── Ketua RT 02 ───────────────────────────────────────
  {
    id:            'kandidat-rs',
    nama:          'Rini Susanti',
    ini:           'RS',
    kategori:      'rt2',
    kategoriLabel: 'Ketua RT 02',
    jabatan:       'Calon Ketua RT 02',
    nomorUrut:     1,
    usia:          39,
    ttl:           'Jakarta, 17 Agustus 1985',
    pendidikan:    'S1 Pendidikan — Universitas Negeri Jakarta',
    pekerjaan:     'Guru SD Negeri',
    alamat:        'Jl. Bougenville No. 8, RT 02',
    pengalaman:    'Ketua PKK RT 02 (2022–2025)',
    visi:          'Mewujudkan RT 02 sebagai lingkungan edukatif, harmonis, dan nyaman untuk keluarga.',
    misi: [
      'Mendirikan taman belajar anak di lingkungan RT',
      'Meningkatkan kesadaran warga akan pentingnya pendidikan',
      'Menciptakan suasana lingkungan yang aman dan ramah anak',
      'Mengelola iuran dan program sosial RT secara transparan',
    ],
    program:  ['Pendidikan', 'Ramah Anak', 'Lingkungan', 'Komunikasi'],
    bg:       '#DBEAFE', tx: '#1D4ED8',
    bar:      '#1558B0', barEnd: '#3B82F6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-jp',
    nama:          'Joko Prasetyo',
    ini:           'JP',
    kategori:      'rt2',
    kategoriLabel: 'Ketua RT 02',
    jabatan:       'Calon Ketua RT 02',
    nomorUrut:     2,
    usia:          45,
    ttl:           'Bekasi, 29 April 1979',
    pendidikan:    'D3 Teknik Elektro — Politeknik Negeri Jakarta',
    pekerjaan:     'Teknisi Listrik & Kontraktor',
    alamat:        'Jl. Bougenville No. 22, RT 02',
    pengalaman:    'Koordinator infrastruktur RT 02 sejak 2020',
    visi:          'Membangun infrastruktur RT 02 yang handal, modern, dan dapat dinikmati seluruh warga.',
    misi: [
      'Memperbaiki jaringan listrik dan penerangan jalan yang tidak merata',
      'Membangun sistem drainase yang bebas banjir',
      'Mendata aset dan fasilitas RT secara digital',
      'Berkoordinasi aktif dengan dinas untuk perbaikan fasilitas umum',
    ],
    program:  ['Listrik', 'Drainase', 'Perawatan', 'Teknologi'],
    bg:       '#CCFBF1', tx: '#0F766E',
    bar:      '#0F766E', barEnd: '#14B8A6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-mp',
    nama:          'Maya Putri',
    ini:           'MP',
    kategori:      'rt2',
    kategoriLabel: 'Ketua RT 02',
    jabatan:       'Calon Ketua RT 02',
    nomorUrut:     3,
    usia:          29,
    ttl:           'Jakarta, 2 Februari 1995',
    pendidikan:    'S1 Komunikasi — Universitas Mercu Buana',
    pekerjaan:     'Content Creator & UMKM Online',
    alamat:        'Jl. Bougenville No. 31, RT 02',
    pengalaman:    'Ketua Karang Taruna RT 02 (2023–2025)',
    visi:          'Membawa semangat anak muda untuk membangun RT 02 yang modern dan kreatif.',
    misi: [
      'Mengaktifkan karang taruna sebagai motor penggerak kegiatan RT',
      'Mempromosikan UMKM warga melalui media sosial',
      'Membuat konten digital informatif tentang kegiatan RT',
      'Mendorong partisipasi generasi muda dalam kepengurusan RT',
    ],
    program:  ['Digital', 'UMKM', 'Kreatif', 'Pemuda'],
    bg:       '#FFEDD5', tx: '#9A3412',
    bar:      '#EA580C', barEnd: '#F97316',
    votes:    0, pct: 0, status: 'pesaing',
  },

  // ── Ketua RT 03 ───────────────────────────────────────
  {
    id:            'kandidat-as',
    nama:          'Agus Setiawan',
    ini:           'AS',
    kategori:      'rt3',
    kategoriLabel: 'Ketua RT 03',
    jabatan:       'Calon Ketua RT 03',
    nomorUrut:     1,
    usia:          50,
    ttl:           'Jakarta, 8 Mei 1974',
    pendidikan:    'S1 Manajemen — Universitas Gunadarma',
    pekerjaan:     'Manajer Operasional Perusahaan Logistik',
    alamat:        'Jl. Cempaka No. 5, RT 03',
    pengalaman:    'Ketua RT 03 petahana (2023–2026), Wakil Ketua RW 05',
    visi:          'Melanjutkan dan meningkatkan program yang telah berjalan demi RT 03 yang lebih baik.',
    misi: [
      'Melanjutkan program keamanan lingkungan yang telah terbukti efektif',
      'Meningkatkan kualitas fasilitas posyandu dan balai RT',
      'Memperluas jaringan kerjasama dengan instansi kelurahan',
      'Mempertahankan transparansi pengelolaan keuangan RT',
    ],
    program:  ['Keamanan', 'Fasilitas', 'Manajemen', 'Sosial'],
    bg:       '#DBEAFE', tx: '#1D4ED8',
    bar:      '#1558B0', barEnd: '#3B82F6',
    votes:    0, pct: 0, status: 'pesaing',
  },
  {
    id:            'kandidat-ln',
    nama:          'Lia Novianti',
    ini:           'LN',
    kategori:      'rt3',
    kategoriLabel: 'Ketua RT 03',
    jabatan:       'Calon Ketua RT 03',
    nomorUrut:     2,
    usia:          34,
    ttl:           'Depok, 19 November 1990',
    pendidikan:    'S2 Kesehatan Lingkungan — Universitas Indonesia',
    pekerjaan:     'Peneliti Kesehatan Lingkungan',
    alamat:        'Jl. Cempaka No. 17, RT 03',
    pengalaman:    'Penggerak program Kampung Iklim RT 03 (2024)',
    visi:          'Mewujudkan RT 03 sebagai kampung sehat berbasis ilmu pengetahuan dan data.',
    misi: [
      'Menerapkan program RT bebas asap rokok di area publik',
      'Mengelola sampah organik menjadi kompos untuk warga',
      'Melakukan pemetaan kesehatan warga secara berkala',
      'Meningkatkan kualitas air bersih dan sanitasi lingkungan',
    ],
    program:  ['Kompos', 'Bebas Rokok', 'Air Bersih', 'Data Warga'],
    bg:       '#CCFBF1', tx: '#0F766E',
    bar:      '#0F766E', barEnd: '#14B8A6',
    votes:    0, pct: 0, status: 'pesaing',
  },
];

// ── ADMIN / PANITIA ───────────────────────────────────────────
// Password default: Admin@2026  (ganti setelah seed!)
export const ADMINS = [
  {
    nama:  'Ketua Panitia',
    email: 'ketua@epemilihan.local',
    password: 'Admin@2026',
  },
  {
    nama:  'Sekretaris Panitia',
    email: 'sekretaris@epemilihan.local',
    password: 'Admin@2026',
  },
  {
    nama:  'Pengawas KPU',
    email: 'pengawas@kelurahan.go.id',
    password: 'Admin@2026',
  },
];

// ── WARGA DUMMY ───────────────────────────────────────────────
// Password default: Warga@2026
// Status bervariasi: verified, pending, rejected
export const WARGA = [
  // RT 01 — verified
  { nik: '3171010101800001', nama: 'Agung Prasetya',    ttl: '1980-01-01', rt: 'rt01', noTelp: '+6281200000001', email: 'agung.p@gmail.com',    status: 'verified' },
  { nik: '3171010101820002', nama: 'Badriyah Salam',    ttl: '1982-02-14', rt: 'rt01', noTelp: '+6281200000002', email: 'badriyah@gmail.com',    status: 'verified' },
  { nik: '3171010101850003', nama: 'Cahyo Nugroho',     ttl: '1985-03-20', rt: 'rt01', noTelp: '+6281200000003', email: 'cahyo.n@gmail.com',     status: 'verified' },
  { nik: '3171010101900004', nama: 'Dian Permatasari',  ttl: '1990-07-08', rt: 'rt01', noTelp: '+6281200000004', email: 'dian.p@gmail.com',      status: 'verified' },
  { nik: '3171010101880005', nama: 'Eko Setiabudi',     ttl: '1988-11-25', rt: 'rt01', noTelp: '+6281200000005', email: 'eko.sb@gmail.com',      status: 'verified' },

  // RT 02 — verified
  { nik: '3171020101830001', nama: 'Fajar Wibowo',      ttl: '1983-04-12', rt: 'rt02', noTelp: '+6281200000006', email: 'fajar.w@gmail.com',     status: 'verified' },
  { nik: '3171020101870002', nama: 'Gita Larasati',     ttl: '1987-09-30', rt: 'rt02', noTelp: '+6281200000007', email: 'gita.l@gmail.com',      status: 'verified' },
  { nik: '3171020101920003', nama: 'Hadi Santoso',      ttl: '1992-06-17', rt: 'rt02', noTelp: '+6281200000008', email: 'hadi.s@gmail.com',      status: 'verified' },
  { nik: '3171020101780004', nama: 'Indah Lestari',     ttl: '1978-12-03', rt: 'rt02', noTelp: '+6281200000009', email: 'indah.l@gmail.com',     status: 'verified' },
  { nik: '3171020101950005', nama: 'Jefri Kurniawan',   ttl: '1995-08-22', rt: 'rt02', noTelp: '+6281200000010', email: 'jefri.k@gmail.com',     status: 'verified' },

  // RT 03 — verified
  { nik: '3171030101810001', nama: 'Kartini Wahyuni',   ttl: '1981-05-21', rt: 'rt03', noTelp: '+6281200000011', email: 'kartini.w@gmail.com',   status: 'verified' },
  { nik: '3171030101860002', nama: 'Lukman Hakim',      ttl: '1986-10-14', rt: 'rt03', noTelp: '+6281200000012', email: 'lukman.h@gmail.com',    status: 'verified' },
  { nik: '3171030101930003', nama: 'Mega Sari',         ttl: '1993-02-28', rt: 'rt03', noTelp: '+6281200000013', email: 'mega.s@gmail.com',      status: 'verified' },
  { nik: '3171030101750004', nama: 'Nanda Firmansyah',  ttl: '1975-07-07', rt: 'rt03', noTelp: '+6281200000014', email: 'nanda.f@gmail.com',     status: 'verified' },
  { nik: '3171030101890005', nama: 'Okta Dewi',         ttl: '1989-03-15', rt: 'rt03', noTelp: '+6281200000015', email: 'okta.d@gmail.com',      status: 'verified' },

  // Pending — belum diverifikasi
  { nik: '3171010101960006', nama: 'Putri Anggraini',   ttl: '1996-01-09', rt: 'rt01', noTelp: '+6281200000016', email: 'putri.a@gmail.com',     status: 'pending'  },
  { nik: '3171020101970007', nama: 'Qomarudin Sidik',   ttl: '1997-04-18', rt: 'rt02', noTelp: '+6281200000017', email: 'qomarudin@gmail.com',   status: 'pending'  },
  { nik: '3171030101980008', nama: 'Rahayu Ningsih',    ttl: '1998-11-11', rt: 'rt03', noTelp: '+6281200000018', email: 'rahayu.n@gmail.com',    status: 'pending'  },

  // Rejected — ditolak
  { nik: '3171010101991009', nama: 'Samsul Arifin',     ttl: '1991-06-06', rt: 'rt01', noTelp: '+6281200000019', email: 'samsul.a@gmail.com',    status: 'rejected', alasanTolak: 'NIK tidak sesuai data kelurahan.' },
];